import 'dart:io';

void main() {
  stdout.write("name   :");
  var name = stdin.readLineSync()!;
  stdout.write("Title   :");
  var title = stdin.readLineSync()!;
  stdout.write("quantity   :");
  var quantity = stdin.readLineSync()!;
  print("${name} ordered ${quantity} ${title} on xyz Clothing store");
  print("\n");
  stdout.write("enter the value is  :");
  var a = int.parse(stdin.readLineSync()!);
  stdout.write("enter the value is  :");
  var b = int.parse(stdin.readLineSync()!);
  print("add  : ${a + b}");
  print("\n");
  print("subtract  : ${a - b}");
  print("multiply  : ${a * b}");
  print("dividle  : ${a / b}");
  print("\n");
  stdout.write("enter the ticket price :");
  var ticketprice = int.parse(stdin.readLineSync()!);
  stdout.write("enter the number of ticket :");
  var numberofticket = int.parse(stdin.readLineSync()!);
  print("tickets price =${ticketprice}");
  print("number of tickets =${numberofticket}");
  print("total ticket price  :${ticketprice * numberofticket}");
  print("\n");
  print("five task");
  stdout.write("enter the value of celsius  :");
  var cel = int.parse(stdin.readLineSync()!);
  var fahren = (cel * 9 / 5) + 32;
  print("celsius is convert to fahrenheit  :${fahren}");
  print("\n");
  print("six task");
  int first = 200, second = 100;
  stdout.write("the price of first item :${first} \nthe price of second item  :${second} ");
  stdout.write("\nnumber of first item  :");
  int fi = int.parse(stdin.readLineSync()!);
  stdout.write("number of second item  :");
  int si = int.parse(stdin.readLineSync()!);
  print("total price of : ${(first * fi) + (second * si)}");
  print("\n");
  print("seven task ");
  final int totalmark = 400;
  stdout.write("the total number is ${totalmark} \nEnter the obtain number  :");
  var obn = int.parse(stdin.readLineSync()!);
  print("the percentage is ${(obn / totalmark) * 100}");
  print("\n");
  print("eigth task");
  double dou = 175.5;
  var riyal = 46.8;
  print("rate of dollar is :${dou}\nrate of riyal :${riyal}");
  stdout.write("enter number dollar :");
  int doll = int.parse(stdin.readLineSync()!);
  stdout.write("enter number riyal :");
  int rit = int.parse(stdin.readLineSync()!);
  print("total covert in pakistan rupees :${(doll * dou) + (rit * riyal)}");
  print("\n");
  print("last task");
  stdout.write("rate of hour  :");
  int hp = int.parse(stdin.readLineSync()!);
  stdout.write("enter number of hours :");
  int hours = int.parse(stdin.readLineSync()!);
  print("total number of price is  :${hp * hours}");
}
